"""Text

Revision ID: 55b8bd6ca707
Revises: None
Create Date: 2016-10-07 13:41:29.509736

"""

# revision identifiers, used by Alembic.
revision = '55b8bd6ca707'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('text',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('sender', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('text')
    ### end Alembic commands ###
